### ISSUE TITLE
Add a templates dir runtime parameter

### ISSUE THREAD

**Issue by abilioesteves** [flaviostutz/ruller-dsl-feature-flag#16]
Today, if you `clone`, `build` and then run `ruller-dsl-feature-flag` the following error will happen:

![image](https://user-images.githubusercontent.com/6494839/86936312-38857b00-c114-11ea-9d9a-adad5aef9089.png)

This happens because it tries to look for templates at the `/app/templates` folder, which most definitely does not exists by default on devs machines.

I think this is hardcoded because the main way to run `ruller-dsl-feature-flag` is with it's Docker image. But that may not always be the case, specially in development time.

**Comment by flaviostutz** [comment]
Great!
