### ISSUE TITLE
Allow source files from folder

### ISSUE THREAD

**Issue by abilioesteves** [flaviostutz/ruller-dsl-feature-flag#22]
We are writing an UI for managing rules created with `ruller-dsl-feature-flag` on our backend.

And we are having to programmatically rewrite our Dockerfile every time a new rule group is added.

I think it would be better to have a source folder option where we just create our rule group files in there, and rebuild the image, without having to modify the Dockerfile every time. Example:

```bash
./ruller-dsl-feature-flag --source ./folder --target ./rules.go --templdir ./templates
```
What do you think, @flaviostutz @milhomens ?

**Comment by flaviostutz** [comment]
That would be great. What about making "source" to use glob patterns?

--source ./test-*
--source ./**/prod/*
--source ./*

https://github.com/yargevad/filepathx

**Comment by abilioesteves** [comment]
Even better! Will open a PR soon...
