### ISSUE TITLE
Add negation operator to DSL

### ISSUE THREAD

**Issue by flaviostutz** [flaviostutz/ruller-dsl-feature-flag#4]
We need something like !contains(..) or input:age!=20 or !randomPerc(10,input:customerid)

**Comment by toinsane** [comment]
Hellow Stutz, do you want that exactly syntax or could it be something like:

- notContains(...) 
- notRandomPerc(10,input:customerid)
- input:age!=20 ( struggling with that in particular )

**Comment by MichaelRSilva** [comment]
@toinsane the following disclaimer (**input:age!=20**) has been adjusted, please look at the comments on issue #5.

**Comment by flaviostutz** [comment]
I thought about "negate" using the "!" symbol because it will have the same semantics as the "!=" and because it is a known operator to programmers.

**Comment by abilioesteves** [comment]
Does the ruller already accepts the usage of parenthesis for defining conditions? This could a complicator for tackling this issue. If not, maybe we can propose a workaround. @flaviostutz

**Comment by abilioesteves** [comment]
For example:
```
{
    "_condition": "(X and Y) or (W and Z)"
}
```

**Comment by flaviostutz** [comment]
Maybe it works, because this DSL engine is just a "string replacer", not a full semantics compiler. We have to test.
I think it is not too hard to implement the negate operator now and simplifies the rule logic for the "users".

**Comment by abilioesteves** [comment]
Ok. I'll proceed with some tests and let you know.

**Comment by abilioesteves** [comment]
@flaviostutz, after various tests (on the new version that fixed the `==` operator), I couldn't find a situation where the negation nor the parentheses don't work.

Apparently this was supported all along. Do you have any specific condition case you would like me to test? I will open a PR with some unit tests.

**Comment by flaviostutz** [comment]
You could please test the conductions on https://github.com/flaviostutz/ruller-dsl-feature-flag/blob/master/sample-json/screens.json, by changing it to the "negate" version of each term in conditions.

**Comment by abilioesteves** [comment]
Yep. It works.

**Comment by abilioesteves** [comment]
@flaviostutz, I think this issue should be closed.
